#!/usr/bin/env bash
# A script to install nginx on a server
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page) using curl,
#     it must return a page that contains the string `Hello World!`

# Install nginx
apt-get -y update
apt-get -y install nginx

# Start nginx
if [[ ! $(pgrep nginx) ]]; then
    service nginx start
fi

# Get the first root directory of nginx from the configuration file
root_dir=$(grep "root" /etc/nginx/sites-available/default | cut -d " " -f 2 | tr -d ";" | head -1)

# Create the directory if it doesn't exist
if [[ ! -d $root_dir ]]; then
    sudo mkdir -p "$root_dir"
fi

# Write `Hello World!` to the index.html file
echo "Hello World!" > "$root_dir"/index.html

# Check if Nginx is running and serving the expected content
response=$(curl -s http://localhost)
if [[ $response == "Hello World!" ]]; then
  echo "Nginx installation and configuration successful!"
else
  echo "Nginx installation or configuration failed."
  exit 1
fi

exit 0
